### ISSUE TITLE
--no-deps does not seem to work

### ISSUE THREAD

**Issue by kokkonisd** [wimglenn/johnnydep#65]
Based on the information I get when running `johnnydep --help`, I'm expecting the `--no-deps` switch to do exactly what it says: `Don't recurse the dependency tree`.
However, when I run it on `macgrind` (which has exactly two "direct" dependencies: `click` and `docker`), I get:
```
$ johnnydep --no-deps macgrind
name                               summary
---------------------------------  ----------------------------------------------------------------------
macgrind                           A containerized version of Valgrind for OSX.
├── click                          Composable command line interface toolkit
└── docker                         A Python library for the Docker Engine API.
    ├── requests!=2.18.0,>=2.14.2  Python HTTP for Humans.
    │   ├── certifi>=2017.4.17     Python package for providing Mozilla's CA Bundle.
    │   ├── chardet<5,>=3.0.2      Universal encoding detector for Python 2 and 3
    │   ├── idna<3,>=2.5           Internationalized Domain Names in Applications (IDNA)
    │   └── urllib3<1.27,>=1.21.1  HTTP library with thread-safe connection pooling, file post, and more.
    └── websocket-client>=0.32.0   WebSocket client for Python with low level API options
```
Which means that it ignores the switch and recurses the dependency tree anyway.
Could this be fixed, please?

Version:
```
$ johnnydep --version
johnnydep v1.7
```

**Comment by wimglenn** [comment]
With the default tree output format, which is a human-readable **tree** format, `--no-deps` will be silently ignored. That's because there would be no useful information to see, only the root node of the tree (i.e. first row of the output).

So `--no-deps` only affects the other output format options (`--output-format {human,json,yaml,python,toml,pinned}`).

Example with yaml:

```
- name: macgrind
  summary: A containerized version of Valgrind for OSX.
  specifier: ''
  requires:
  - click
  - docker
  required_by: []
  import_names:
  - macgrind
  homepage: https://github.com/kokkonisd/macgrind
  extras_available: []
  extras_requested: []
  project_name: macgrind
  license: GNU General Public License v3 (GPLv3)
  versions_available:
  - 0.0.1
  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
  - 1.0.4
  version_installed: null
  version_latest: 1.0.4
  version_latest_in_spec: 1.0.4
  download_link: https://files.pythonhosted.org/packages/80/7f/a955b8076304dc14afe100ea41b17b8da78b6f2015aaca43d83f95f8ffaf/macgrind-1.0.4-py3-none-any.whl
  checksum: sha256=59e96359ab39f7d5f2aa382ae8a8b290de2e388b3b05880f368a53169ef78b4c
```

I will add a note to `johnnydep --help` output to indicate that `--no-deps` is not used for the "human" output format option.
